Repository devcontainers-extra/features, pull requests merged in 2024-11, with the labels that each got.

#65 fix(homebrew-package): fix tests and unarchive
  archive/test/homebrew-package/test_git_based_version.sh
  src/homebrew-package/README.md
  src/homebrew-package/devcontainer-feature.json
  src/homebrew-package/install.sh
  src/homebrew-package/library_scripts.sh
  test/homebrew-package/scenarios.json
  test/homebrew-package/test_file_limit.sh
  test/homebrew-package/test_latest.sh
  test/homebrew-package/test_specific_version.sh
  test/homebrew-package/test_universal.sh
Labels: bug

#63 Add pipx-package helper to CONTRIBUTING.md, link from README
  CONTRIBUTING.md
  README.md
Labels: documentation

#52 fix(haskell): install Haskell libraries
  src/haskell/devcontainer-feature.json
  src/haskell/install.sh
  test/haskell/scenarios.json
  test/haskell/test_libraries.sh
Labels: existing feature

#73 chore(ci): clean disk only for specific features
  .github/workflows/test.yaml
Labels: enhancement
